spring:
  application:
    name: loginServer
server:
  port: 8400

## eureka
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://admin:pass@my.eureka.com:8100/eureka
    healthcheck:
      enabled: true

